-- GENERATED by db/seed/emit-seed-sql.ts - do not edit by hand.
-- Values come from the modpack's own server.properties (50 keys),
-- so the seeded config is exactly what the pack author shipped and tested.
-- The pack's identity comes from deploy/modpack.lock, so this file and the
-- verified archive cannot disagree about which pack is running.
-- Tiers and reasons come from packages/core/src/config/tiers.ts (ADR-0003),
-- which is policy in source: a tier change should arrive through review.

BEGIN;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('allow-flight', 'true', 'LOCKED', 'ต้องเป็น true ไม่งั้นผู้เล่นที่ใช้ elytra ขี่สัตว์บิน หรือของจาก mod ที่ ทำให้ลอยตัว จะถูกเซิร์ฟเตะออกด้วยข้อหาโกง ทั้งที่เล่นตามปกติ', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('allow-nether', 'true', 'GUARDED', 'เนเธอร์เป็นส่วนหนึ่งของเส้นทางความก้าวหน้าและของเควสต์หลายอัน ปิดแล้วผู้เล่นจะตันกลางเกมโดยไม่มีอะไรอธิบายว่าทำไม', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('broadcast-console-to-ops', 'true', 'FREE', 'ส่งข้อความ console ให้ op เห็นในเกม', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('broadcast-rcon-to-ops', 'true', 'FREE', 'ส่งผลลัพธ์คำสั่งที่มาทาง RCON ให้ op เห็นในเกม', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('difficulty', 'normal', 'GUARDED', 'Homestead เป็น pack แนวอยู่สบาย ไม่ได้ปรับสมดุลรอบความยากสูงแบบ pack สาย เอาชีวิตรอด เปลี่ยนได้ตามใจกลุ่มผู้เล่น แต่กระทบทุกคนบนเซิร์ฟพร้อมกัน', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('enable-command-block', 'true', 'LOCKED', 'ต้องเป็น true เพราะโครงสร้างและรางวัลเควสต์ของ pack ใช้ command block ปิดแล้วบางโครงสร้างจะสร้างไม่ครบและเควสต์บางอันจะให้ของไม่ได้', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('enable-jmx-monitoring', 'false', 'LOCKED', 'คีย์นี้ยังไม่ได้จัดระดับไว้ ระบบจึงล็อกไว้โดยปริยายเพื่อความปลอดภัย ถ้าต้องการให้แก้ได้ ต้องเพิ่มลง TIERS ในโค้ดผ่านการรีวิว', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('enable-query', 'false', 'GUARDED', 'เปิดแล้วต้องเปิดพอร์ต UDP ใน ufw ด้วยถึงจะใช้ได้ และระบบสถานะของเราใช้ Server List Ping อยู่แล้วจึงไม่จำเป็น', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

-- OVERRIDDEN: pack ships 'false' — the Control Plane speaks to the Game Server over RCON and nothing else (ADR-0002)
INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('enable-rcon', 'true', 'LOCKED', 'ปิดแล้วบอท Discord และปุ่ม Apply จะสั่งงานเซิร์ฟไม่ได้เลย — เท่ากับปิดระบบควบคุมทั้งระบบ', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('enable-status', 'true', 'LOCKED', 'คีย์นี้ยังไม่ได้จัดระดับไว้ ระบบจึงล็อกไว้โดยปริยายเพื่อความปลอดภัย ถ้าต้องการให้แก้ได้ ต้องเพิ่มลง TIERS ในโค้ดผ่านการรีวิว', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('enforce-whitelist', 'true', 'GUARDED', 'เปิดแล้วคนที่ถูกถอดออกจาก whitelist จะถูกเตะออกทันทีระหว่างเล่น ไม่ใช่แค่เข้าใหม่ไม่ได้', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('entity-broadcast-range-percentage', '100', 'FREE', 'ระยะที่ผู้เล่นเห็นสัตว์และของที่ตกอยู่ ลดแล้วเบาเครื่องขึ้นและไม่กระทบ กติกา แค่ของจะโผล่ให้เห็นตอนเข้าใกล้กว่าเดิม', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('force-gamemode', 'false', 'GUARDED', 'บังคับโหมดเกมของผู้เล่นทุกคนตอนเข้าเซิร์ฟ ทับค่าที่แต่ละคนเคยเป็น', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('function-permission-level', '2', 'GUARDED', 'ระดับสิทธิ์ที่ datapack function รันได้ ลดแล้วเควสต์และโครงสร้างที่เรียก คำสั่งระดับสูงจะเงียบ ๆ ทำงานไม่ครบ', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('gamemode', 'survival', 'GUARDED', 'survival คือโหมดที่ pack ออกแบบมา เปลี่ยนเป็น creative จะทำให้ทั้งเซิร์ฟ ได้ของฟรีหมดและเควสต์เสียความหมาย', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('generate-structures', 'true', 'LOCKED', 'คีย์นี้ยังไม่ได้จัดระดับไว้ ระบบจึงล็อกไว้โดยปริยายเพื่อความปลอดภัย ถ้าต้องการให้แก้ได้ ต้องเพิ่มลง TIERS ในโค้ดผ่านการรีวิว', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('generator-settings', '', 'LOCKED', 'คีย์นี้ยังไม่ได้จัดระดับไว้ ระบบจึงล็อกไว้โดยปริยายเพื่อความปลอดภัย ถ้าต้องการให้แก้ได้ ต้องเพิ่มลง TIERS ในโค้ดผ่านการรีวิว', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('hardcore', 'false', 'GUARDED', 'เปิดแล้วผู้เล่นที่ตายจะถูกแบนถาวรจากโลกนั้น เป็นการเปลี่ยนกติกาที่ ย้อนความเสียหายให้ผู้เล่นไม่ได้', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

-- OVERRIDDEN: pack ships 'world' — the world directory should name the pack; must match MC_WORLD_DIR and backup.sh
INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('level-name', 'Homestead', 'LOCKED', 'เปลี่ยนแล้วเซิร์ฟจะสร้างโลกใหม่ว่างเปล่า โลกเดิมกลายเป็นไฟล์ทิ้ง เสียทั้ง progress ผู้เล่นและเวลาสร้างแผนที่ทั้งหมด กู้ไม่ได้', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('level-seed', '', 'LOCKED', 'คีย์นี้ยังไม่ได้จัดระดับไว้ ระบบจึงล็อกไว้โดยปริยายเพื่อความปลอดภัย ถ้าต้องการให้แก้ได้ ต้องเพิ่มลง TIERS ในโค้ดผ่านการรีวิว', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('level-type', 'default', 'LOCKED', 'Homestead วางภูมิประเทศผ่าน Tectonic และ TerraBlender บนพื้นฐานของ minecraft:normal เปลี่ยนเป็น flat หรือ large_biomes แล้วไบโอมและ โครงสร้างของ pack จะไม่ตรงกับโลกที่ผู้เล่นอยู่', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('max-build-height', '256', 'LOCKED', 'คีย์นี้ยังไม่ได้จัดระดับไว้ ระบบจึงล็อกไว้โดยปริยายเพื่อความปลอดภัย ถ้าต้องการให้แก้ได้ ต้องเพิ่มลง TIERS ในโค้ดผ่านการรีวิว', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('max-players', '10', 'FREE', 'จำนวนผู้เล่นพร้อมกันสูงสุด เครื่องนี้รัน heap 8 GB ซึ่งเป็นเพดานของ Host ไม่ใช่ค่าที่เหลือเฟือ ตั้งสูงได้แต่ควรดู TPS และ RSS ประกอบ', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

-- OVERRIDDEN: pack ships '120000' — watchdog must not fire during chunk generation (CLAUDE.md prohibition 1, ADR-0005)
INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('max-tick-time', '-1', 'LOCKED', 'ต้องเป็น -1 เพราะการสร้าง chunk ของ pack นี้ใช้เวลานานกว่าค่ามาตรฐาน ถ้าตั้งค่าอื่น watchdog จะเข้าใจผิดว่าเซิร์ฟแครชแล้วฆ่าตัวเองกลางการเขียนโลก', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('max-world-size', '29999984', 'LOCKED', 'กำหนดขอบเขตที่โลกสร้างต่อได้ ลดลงหลังจากผู้เล่นออกไปไกลแล้ว จะทำให้ พื้นที่ที่สร้างไว้แล้วอยู่นอกขอบและเดินทางกลับเข้าไปไม่ได้', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('motd', 'Homestead Server', 'FREE', 'ข้อความที่แสดงในหน้ารายการเซิร์ฟของผู้เล่น', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('network-compression-threshold', '256', 'FREE', 'ขนาดแพ็กเก็ตที่เริ่มบีบอัด เป็นการจูนประสิทธิภาพ ไม่กระทบกติกาเกม', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('online-mode', 'true', 'GUARDED', 'ปิดแล้วใครก็สวมรอยเป็นชื่อใครก็ได้ รวมถึงชื่อแอดมิน เปิดไว้เสมอ ยกเว้นมีเหตุผลที่เข้าใจผลกระทบเต็มที่', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('op-permission-level', '4', 'GUARDED', 'กำหนดว่า op ทำอะไรได้บ้าง ลดแล้วคำสั่งจัดการเซิร์ฟบางส่วนจะใช้ไม่ได้', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('player-idle-timeout', '0', 'FREE', 'เตะผู้เล่นที่ไม่ขยับออกหลังกี่นาที (0 = ไม่เตะ)', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('prevent-proxy-connections', 'false', 'GUARDED', 'เปิดแล้วผู้เล่นที่ต่อผ่าน VPN บางแบบจะเข้าไม่ได้', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('pvp', 'true', 'GUARDED', 'เปลี่ยนกติกาการเล่นของทุกคนบนเซิร์ฟทันที', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('query.port', '25565', 'LOCKED', 'คีย์นี้ยังไม่ได้จัดระดับไว้ ระบบจึงล็อกไว้โดยปริยายเพื่อความปลอดภัย ถ้าต้องการให้แก้ได้ ต้องเพิ่มลง TIERS ในโค้ดผ่านการรีวิว', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('rate-limit', '0', 'LOCKED', 'คีย์นี้ยังไม่ได้จัดระดับไว้ ระบบจึงล็อกไว้โดยปริยายเพื่อความปลอดภัย ถ้าต้องการให้แก้ได้ ต้องเพิ่มลง TIERS ในโค้ดผ่านการรีวิว', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('rcon.password', '', 'LOCKED', 'ตั้งจาก .env บนเครื่องเท่านั้น ไม่แก้ผ่านเว็บ', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('rcon.port', '25575', 'LOCKED', 'ใช้ภายใน Docker network เท่านั้น ไม่เคย publish ออกอินเทอร์เน็ต', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('resource-pack', '', 'LOCKED', 'คีย์นี้ยังไม่ได้จัดระดับไว้ ระบบจึงล็อกไว้โดยปริยายเพื่อความปลอดภัย ถ้าต้องการให้แก้ได้ ต้องเพิ่มลง TIERS ในโค้ดผ่านการรีวิว', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('resource-pack-sha1', '', 'LOCKED', 'คีย์นี้ยังไม่ได้จัดระดับไว้ ระบบจึงล็อกไว้โดยปริยายเพื่อความปลอดภัย ถ้าต้องการให้แก้ได้ ต้องเพิ่มลง TIERS ในโค้ดผ่านการรีวิว', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('server-ip', '', 'LOCKED', 'คีย์นี้ยังไม่ได้จัดระดับไว้ ระบบจึงล็อกไว้โดยปริยายเพื่อความปลอดภัย ถ้าต้องการให้แก้ได้ ต้องเพิ่มลง TIERS ในโค้ดผ่านการรีวิว', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('server-port', '25565', 'LOCKED', 'ผูกกับ SRV record บน Cloudflare และกฎ ufw บนเครื่อง เปลี่ยนที่นี่ที่เดียว ผู้เล่นจะเข้าไม่ได้ทั้งหมด', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('snooper-enabled', 'false', 'LOCKED', 'คีย์นี้ยังไม่ได้จัดระดับไว้ ระบบจึงล็อกไว้โดยปริยายเพื่อความปลอดภัย ถ้าต้องการให้แก้ได้ ต้องเพิ่มลง TIERS ในโค้ดผ่านการรีวิว', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('spawn-animals', 'true', 'FREE', 'เปิด/ปิดการเกิดสัตว์', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('spawn-monsters', 'true', 'FREE', 'เปิด/ปิดการเกิดมอนสเตอร์', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('spawn-npcs', 'true', 'FREE', 'เปิด/ปิดการเกิด villager', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('spawn-protection', '8', 'GUARDED', 'กำหนดว่าผู้เล่นทั่วไปแก้บล็อกรอบจุดเกิดได้ไกลแค่ไหน', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('sync-chunk-writes', 'true', 'LOCKED', 'ต้องเป็น true การปิดทำให้การเขียน chunk ไม่รอดิสก์ยืนยัน ซึ่งเร็วขึ้นจริง แต่ไฟไหม้กลางคันเมื่อไหร่ region file เสียทั้งก้อน แลกไม่คุ้ม', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('text-filtering-config', '', 'LOCKED', 'คีย์นี้ยังไม่ได้จัดระดับไว้ ระบบจึงล็อกไว้โดยปริยายเพื่อความปลอดภัย ถ้าต้องการให้แก้ได้ ต้องเพิ่มลง TIERS ในโค้ดผ่านการรีวิว', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('use-native-transport', 'true', 'LOCKED', 'คีย์นี้ยังไม่ได้จัดระดับไว้ ระบบจึงล็อกไว้โดยปริยายเพื่อความปลอดภัย ถ้าต้องการให้แก้ได้ ต้องเพิ่มลง TIERS ในโค้ดผ่านการรีวิว', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('view-distance', '12', 'GUARDED', 'ระยะที่เซิร์ฟส่ง chunk ให้ผู้เล่นเห็น เป็นตัวกินแรมและ CPU ที่ใหญ่ที่สุด ตัวหนึ่ง เครื่องนี้มีแรมจำกัด เพิ่มแล้วควรดู TPS และ RSS ประกอบเสมอ', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('white-list', 'false', 'GUARDED', 'เปิดแล้วคนที่ไม่อยู่ในรายชื่อเข้าไม่ได้ทันที รวมถึงคนที่กำลังเล่นอยู่', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

-- Keys this pack does not have.
--
-- The renderer writes EVERY row in config_key to server.properties without
-- filtering, so a key left behind by a previous modpack keeps being rendered
-- onto a server that has never heard of it. Dregora's `hellworld` is the
-- reason this clause exists: it is not a property of vanilla 1.20.1 at all.
DELETE FROM config_key WHERE key NOT IN ('allow-flight', 'allow-nether', 'broadcast-console-to-ops', 'broadcast-rcon-to-ops', 'difficulty', 'enable-command-block', 'enable-jmx-monitoring', 'enable-query', 'enable-rcon', 'enable-status', 'enforce-whitelist', 'entity-broadcast-range-percentage', 'force-gamemode', 'function-permission-level', 'gamemode', 'generate-structures', 'generator-settings', 'hardcore', 'level-name', 'level-seed', 'level-type', 'max-build-height', 'max-players', 'max-tick-time', 'max-world-size', 'motd', 'network-compression-threshold', 'online-mode', 'op-permission-level', 'player-idle-timeout', 'prevent-proxy-connections', 'pvp', 'query.port', 'rate-limit', 'rcon.password', 'rcon.port', 'resource-pack', 'resource-pack-sha1', 'server-ip', 'server-port', 'snooper-enabled', 'spawn-animals', 'spawn-monsters', 'spawn-npcs', 'spawn-protection', 'sync-chunk-writes', 'text-filtering-config', 'use-native-transport', 'view-distance', 'white-list');

-- Which half of this row the seed owns.
--
-- Everything describing the PACK is re-seeded: the admin panel has no input
-- for any of it, so there is no admin edit to protect — and leaving it on
-- conflict-do-nothing is how the row went on naming the previous modpack
-- long after the pack had changed.
--
-- Everything the operator owns — server_address, discord_url, the icon,
-- rules_markdown — is written once and never overwritten here.
INSERT INTO server_info
  (id, modpack_name, modpack_version, minecraft_version, loader_name, loader_version,
   download_url, wiki_url, server_address, updated_by)
VALUES
  (1, 'Homestead', '1.3.7', '1.20.1',
   'Fabric', '0.18.4',
   'https://www.curseforge.com/minecraft/modpacks/homestead-cozy', 'https://cozystudios.org/homestead/intro/', 'tapestopnight.com', 'seed')
ON CONFLICT (id) DO UPDATE SET
  modpack_name = EXCLUDED.modpack_name,
  modpack_version = EXCLUDED.modpack_version,
  minecraft_version = EXCLUDED.minecraft_version,
  loader_name = EXCLUDED.loader_name,
  loader_version = EXCLUDED.loader_version,
  download_url = EXCLUDED.download_url,
  wiki_url = EXCLUDED.wiki_url,
  updated_by = 'seed',
  updated_at = now();

COMMIT;
