-- GENERATED by db/seed/emit-seed-sql.ts - do not edit by hand.
-- Values come from the modpack's own server.properties (40 keys),
-- so the seeded config is exactly what the pack author shipped and tested.
-- Tiers and reasons come from packages/core/src/config/tiers.ts (ADR-0003),
-- which is policy in source: a tier change should arrive through review.

BEGIN;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('spawn-protection', '16', 'GUARDED', 'กำหนดว่าผู้เล่นทั่วไปแก้บล็อกรอบจุดเกิดได้ไกลแค่ไหน', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('max-tick-time', '-1', 'LOCKED', 'ต้องเป็น -1 เพราะโครงสร้างใหญ่ของ OTG ใช้เวลาสร้างเป็นนาที ถ้าตั้งค่าอื่น Forge จะเข้าใจผิดว่าเซิร์ฟแครชแล้วฆ่าตัวเองกลางการสร้างโลก', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('generator-settings', '', 'LOCKED', 'คีย์นี้ยังไม่ได้จัดระดับไว้ ระบบจึงล็อกไว้โดยปริยายเพื่อความปลอดภัย ถ้าต้องการให้แก้ได้ ต้องเพิ่มลง TIERS ในโค้ดผ่านการรีวิว', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('force-gamemode', 'false', 'GUARDED', 'บังคับโหมดเกมของผู้เล่นทุกคนตอนเข้าเซิร์ฟ ทับค่าที่แต่ละคนเคยเป็น', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('allow-nether', 'true', 'GUARDED', 'Dregora มีเนเธอร์ที่ออกแบบเองและ RLCraft ใช้เนเธอร์เป็นส่วนหนึ่งของ เส้นทางความก้าวหน้า ปิดแล้วผู้เล่นจะตันกลางเกม', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('gamemode', '0', 'GUARDED', '0 = survival ซึ่งเป็นโหมดที่ RLCraft ออกแบบมา เปลี่ยนเป็น creative จะทำให้ทั้งเซิร์ฟได้ของฟรีหมด', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('broadcast-console-to-ops', 'true', 'FREE', 'ส่งข้อความ console ให้ op เห็นในเกม', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('enable-query', 'false', 'GUARDED', 'เปิดแล้วต้องเปิดพอร์ต UDP ใน ufw ด้วยถึงจะใช้ได้ และระบบสถานะของเราใช้ Server List Ping อยู่แล้วจึงไม่จำเป็น', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('player-idle-timeout', '0', 'FREE', 'เตะผู้เล่นที่ไม่ขยับออกหลังกี่นาที (0 = ไม่เตะ)', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('difficulty', '3', 'GUARDED', 'RLCraft ปรับสมดุลมาบนความยาก 3 ลดแล้วเกมจะง่ายกว่าที่ผู้ออกแบบตั้งใจ', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('spawn-monsters', 'true', 'FREE', 'เปิด/ปิดการเกิดมอนสเตอร์', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('op-permission-level', '4', 'GUARDED', 'กำหนดว่า op ทำอะไรได้บ้าง ลดแล้วคำสั่งจัดการเซิร์ฟบางส่วนจะใช้ไม่ได้', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('pvp', 'true', 'GUARDED', 'เปลี่ยนกติกาการเล่นของทุกคนบนเซิร์ฟทันที', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('snooper-enabled', 'false', 'FREE', 'ส่งสถิติการใช้งานให้ Mojang ปิดไว้ก็ได้ ไม่กระทบอะไร', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('level-type', 'OTG', 'LOCKED', 'ต้องเป็น OTG เพื่อให้ OpenTerrainGenerator ทำงาน ถ้าเปลี่ยน โลกจะกลับไปใช้ generation แบบวานิลลา ภูมิประเทศ Dregora หายทั้งหมด', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('hardcore', 'false', 'GUARDED', 'เปิดแล้วผู้เล่นที่ตายจะถูกแบนถาวรจากโลกนั้น เป็นการเปลี่ยนกติกาที่ ย้อนความเสียหายให้ผู้เล่นไม่ได้', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('enable-command-block', 'true', 'LOCKED', 'ต้องเป็น true ไม่งั้น villager จะไม่ spawn ในโครงสร้างที่ generate ขึ้นมา', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('max-players', '20', 'FREE', 'จำนวนผู้เล่นพร้อมกันสูงสุด เครื่องนี้รัน heap 7 GB (ADR-0012) ซึ่งรองรับได้สบายราว 10-15 คน ตั้งสูงกว่านั้นได้แต่ควรดู TPS ประกอบ', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('network-compression-threshold', '256', 'FREE', 'ขนาดแพ็กเก็ตที่เริ่มบีบอัด เป็นการจูนประสิทธิภาพ ไม่กระทบกติกาเกม', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('resource-pack-sha1', '', 'LOCKED', 'คีย์นี้ยังไม่ได้จัดระดับไว้ ระบบจึงล็อกไว้โดยปริยายเพื่อความปลอดภัย ถ้าต้องการให้แก้ได้ ต้องเพิ่มลง TIERS ในโค้ดผ่านการรีวิว', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('max-world-size', '29999984', 'LOCKED', 'ลดต่ำกว่า 20,000 แล้ว teleporter ในเกมจะพัง ตามที่ readme ของ modpack เตือนไว้', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('server-port', '25565', 'LOCKED', 'ผูกกับ SRV record บน Cloudflare และกฎ ufw บนเครื่อง เปลี่ยนที่นี่ที่เดียว ผู้เล่นจะเข้าไม่ได้ทั้งหมด', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('texture-pack', '', 'LOCKED', 'คีย์นี้ยังไม่ได้จัดระดับไว้ ระบบจึงล็อกไว้โดยปริยายเพื่อความปลอดภัย ถ้าต้องการให้แก้ได้ ต้องเพิ่มลง TIERS ในโค้ดผ่านการรีวิว', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('server-ip', '', 'LOCKED', 'คีย์นี้ยังไม่ได้จัดระดับไว้ ระบบจึงล็อกไว้โดยปริยายเพื่อความปลอดภัย ถ้าต้องการให้แก้ได้ ต้องเพิ่มลง TIERS ในโค้ดผ่านการรีวิว', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('spawn-npcs', 'true', 'FREE', 'เปิด/ปิดการเกิด villager', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('allow-flight', 'true', 'LOCKED', 'ต้องเป็น true ไม่งั้นผู้เล่นที่ขี่สัตว์บินหรือใช้ fairy ring จะถูกเซิร์ฟเตะออก', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('level-name', 'DregoraRL', 'LOCKED', 'เปลี่ยนแล้ว Forge จะสร้างโลกใหม่ว่างเปล่า โลกเดิมกลายเป็นไฟล์ทิ้ง เสียทั้ง progress ผู้เล่นและเวลา pre-generation ทั้งหมด กู้ไม่ได้', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('view-distance', '10', 'GUARDED', 'readme ระบุว่า 10 คือค่าที่เข้ากันได้เต็มที่ ลดเป็น 8 หรือ 6 ประหยัดแรมได้ แต่ทำให้ระบบ spawn/despawn มอนสเตอร์เพี้ยน', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('hellworld', 'true', 'LOCKED', 'คีย์นี้ยังไม่ได้จัดระดับไว้ ระบบจึงล็อกไว้โดยปริยายเพื่อความปลอดภัย ถ้าต้องการให้แก้ได้ ต้องเพิ่มลง TIERS ในโค้ดผ่านการรีวิว', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('resource-pack', '', 'LOCKED', 'คีย์นี้ยังไม่ได้จัดระดับไว้ ระบบจึงล็อกไว้โดยปริยายเพื่อความปลอดภัย ถ้าต้องการให้แก้ได้ ต้องเพิ่มลง TIERS ในโค้ดผ่านการรีวิว', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('spawn-animals', 'true', 'FREE', 'เปิด/ปิดการเกิดสัตว์', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('white-list', 'false', 'GUARDED', 'เปิดแล้วคนที่ไม่อยู่ในรายชื่อเข้าไม่ได้ทันที รวมถึงคนที่กำลังเล่นอยู่', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('generate-structures', 'true', 'LOCKED', 'คีย์นี้ยังไม่ได้จัดระดับไว้ ระบบจึงล็อกไว้โดยปริยายเพื่อความปลอดภัย ถ้าต้องการให้แก้ได้ ต้องเพิ่มลง TIERS ในโค้ดผ่านการรีวิว', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('online-mode', 'true', 'GUARDED', 'ปิดแล้วใครก็สวมรอยเป็นชื่อใครก็ได้ รวมถึงชื่อแอดมิน เปิดไว้เสมอ ยกเว้นมีเหตุผลที่เข้าใจผลกระทบเต็มที่', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('max-build-height', '256', 'LOCKED', 'คีย์นี้ยังไม่ได้จัดระดับไว้ ระบบจึงล็อกไว้โดยปริยายเพื่อความปลอดภัย ถ้าต้องการให้แก้ได้ ต้องเพิ่มลง TIERS ในโค้ดผ่านการรีวิว', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('level-seed', '', 'LOCKED', 'คีย์นี้ยังไม่ได้จัดระดับไว้ ระบบจึงล็อกไว้โดยปริยายเพื่อความปลอดภัย ถ้าต้องการให้แก้ได้ ต้องเพิ่มลง TIERS ในโค้ดผ่านการรีวิว', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('prevent-proxy-connections', 'false', 'GUARDED', 'เปิดแล้วผู้เล่นที่ต่อผ่าน VPN บางแบบจะเข้าไม่ได้', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('use-native-transport', 'true', 'LOCKED', 'คีย์นี้ยังไม่ได้จัดระดับไว้ ระบบจึงล็อกไว้โดยปริยายเพื่อความปลอดภัย ถ้าต้องการให้แก้ได้ ต้องเพิ่มลง TIERS ในโค้ดผ่านการรีวิว', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('enable-rcon', 'false', 'LOCKED', 'ปิดแล้วบอท Discord และปุ่ม Apply จะสั่งงานเซิร์ฟไม่ได้เลย — เท่ากับปิดระบบควบคุมทั้งระบบ', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES
  ('motd', 'RLCraft Dregora 1.1.2b, from the depths of the nether(lands)', 'FREE', 'ข้อความที่แสดงในหน้ารายการเซิร์ฟของผู้เล่น', 'seed')
ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;

INSERT INTO server_info
  (id, modpack_name, modpack_version, minecraft_version, forge_version, server_address, updated_by)
VALUES
  (1, 'RLCraft Dregora', 'v1.1.2b', '1.12.2', '14.23.5.2860', 'tapestopnight.com', 'seed')
ON CONFLICT (id) DO NOTHING;

COMMIT;
