/**
 * Emit the seed as SQL, so it can be applied with psql alone.
 *
 * Why this exists: the Host has no Node, and Postgres is deliberately not
 * port-published, so seed.ts cannot reach the database from either side yet.
 * From Phase 5 the correct route is `docker compose run --rm web npm run
 * db:seed`, using the app image that will exist by then. Until that image
 * exists, this keeps the tier table single-sourced in TypeScript while
 * producing something psql can apply and a human can read before it runs.
 *
 *   node db/seed/emit-seed-sql.ts <pack-original> > db/seed/0001-seed.sql
 */
import { readFileSync } from "node:fs";

import { parseProperties, tierFor } from "../../packages/core/src/config/index.ts";

const source = process.argv[2];
if (!source) {
  console.error("usage: emit-seed-sql.ts <path-to-pack-server.properties>");
  process.exit(2);
}

const props = parseProperties(readFileSync(source, "utf8"));
if (props.size === 0) {
  console.error(`no properties parsed from ${source}`);
  process.exit(2);
}

const q = (s: string) => `'${s.replaceAll("'", "''")}'`;

const out: string[] = [
  "-- GENERATED by db/seed/emit-seed-sql.ts - do not edit by hand.",
  `-- Values come from the modpack's own server.properties (${props.size} keys),`,
  "-- so the seeded config is exactly what the pack author shipped and tested.",
  "-- Tiers and reasons come from packages/core/src/config/tiers.ts (ADR-0003),",
  "-- which is policy in source: a tier change should arrive through review.",
  "",
  "BEGIN;",
  "",
];

for (const [key, value] of props) {
  const { tier, reason } = tierFor(key);
  out.push(
    "INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES",
    `  (${q(key)}, ${q(value)}, ${q(tier)}, ${q(reason)}, 'seed')`,
    // Deliberately does not touch `value`: an admin's change through the panel
    // is authoritative, and re-seeding must never silently revert it.
    "ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;",
    "",
  );
}

out.push(
  "INSERT INTO server_info",
  "  (id, modpack_name, modpack_version, minecraft_version, forge_version, server_address, updated_by)",
  "VALUES",
  "  (1, 'RLCraft Dregora', 'v1.1.2b', '1.12.2', '14.23.5.2860', 'tapestopnight.com', 'seed')",
  "ON CONFLICT (id) DO NOTHING;",
  "",
  "COMMIT;",
);

console.log(out.join("\n"));
