/**
 * Emit the seed as SQL, so it can be applied with psql alone.
 *
 * Why this exists: the Host has no Node, and Postgres is deliberately not
 * port-published, so seed.ts cannot reach the database from either side yet.
 * From Phase 5 the correct route is `docker compose run --rm web npm run
 * db:seed`, using the app image that will exist by then. Until that image
 * exists, this keeps the tier table single-sourced in TypeScript while
 * producing something psql can apply and a human can read before it runs.
 *
 *   node db/seed/emit-seed-sql.ts <pack-original> > db/seed/0001-seed.sql
 */
import { readFileSync } from "node:fs";

import { parseProperties, tierFor } from "../../packages/core/src/config/index.ts";
import { packIdentity } from "./pack-identity.ts";
import { DEPLOYMENT_OVERRIDES, seededValue } from "./deployment-overrides.ts";

const source = process.argv[2];
if (!source) {
  console.error("usage: emit-seed-sql.ts <path-to-pack-server.properties>");
  process.exit(2);
}

const props = parseProperties(readFileSync(source, "utf8"));
if (props.size === 0) {
  console.error(`no properties parsed from ${source}`);
  process.exit(2);
}

const q = (s: string) => `'${s.replaceAll("'", "''")}'`;

const out: string[] = [
  "-- GENERATED by db/seed/emit-seed-sql.ts - do not edit by hand.",
  "--",
  "-- ⚠ THIS FILE DOES NOT RESET VALUES, AND AFTER A PACK CHANGE THAT IS NOT",
  "-- ENOUGH ON ITS OWN.",
  "--",
  "-- The ON CONFLICT clauses below update tier and reason but deliberately",
  "-- leave `value` alone, because an admin's change through the panel is",
  "-- authoritative and a routine re-seed must not silently revert it.",
  "--",
  "-- On a PACK CHANGE that protection points the wrong way: every existing row",
  "-- holds the previous pack's value. Seeding alone would leave level-type=OTG",
  "-- and level-name pointing at the old world on a server that has neither, and",
  "-- ADR-0002 means nobody would catch it by reading server.properties — the",
  "-- file is output, and it would look exactly as authoritative as a correct one.",
  "--",
  "-- So when the pack changes, clear the table first and let this file rebuild it:",
  "--",
  "--   docker exec -i tapestopnight-db psql -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\" \\",
  "--     -c 'DELETE FROM config_key;'",
  "--",
  "-- Deliberately NOT part of this file. It destroys every admin edit, which is",
  "-- right exactly once per pack and wrong every other time this file is run.",
  `-- Values come from the modpack's own server.properties (${props.size} keys),`,
  "-- so the seeded config is exactly what the pack author shipped and tested.",
  "-- The pack's identity comes from deploy/modpack.lock, so this file and the",
  "-- verified archive cannot disagree about which pack is running.",
  "-- Tiers and reasons come from packages/core/src/config/tiers.ts (ADR-0003),",
  "-- which is policy in source: a tier change should arrive through review.",
  "",
  "BEGIN;",
  "",
];

for (const [key, packValue] of props) {
  const { tier, reason } = tierFor(key);
  const value = seededValue(key, packValue);
  const override = DEPLOYMENT_OVERRIDES[key];
  if (override) {
    // Loud in the generated SQL too. Somebody reading this file to answer
    // "why is this not what the pack ships" should not have to find the
    // TypeScript that produced it.
    out.push(`-- OVERRIDDEN: pack ships ${q(packValue)} — ${override.why}`);
  }
  out.push(
    "INSERT INTO config_key (key, value, tier, reason, updated_by) VALUES",
    `  (${q(key)}, ${q(value)}, ${q(tier)}, ${q(reason)}, 'seed')`,
    // Deliberately does not touch `value`: an admin's change through the panel
    // is authoritative, and re-seeding must never silently revert it.
    "ON CONFLICT (key) DO UPDATE SET tier = EXCLUDED.tier, reason = EXCLUDED.reason;",
    "",
  );
}

const pack = packIdentity();

out.push(
  "-- Keys this pack does not have.",
  "--",
  "-- The renderer writes EVERY row in config_key to server.properties without",
  "-- filtering, so a key left behind by a previous modpack keeps being rendered",
  "-- onto a server that has never heard of it. Dregora's `hellworld` is the",
  "-- reason this clause exists: it is not a property of vanilla 1.20.1 at all.",
  `DELETE FROM config_key WHERE key NOT IN (${[...props.keys()].map(q).join(", ")});`,
  "",
  "-- Which half of this row the seed owns.",
  "--",
  "-- Everything describing the PACK is re-seeded: the admin panel has no input",
  "-- for any of it, so there is no admin edit to protect — and leaving it on",
  "-- conflict-do-nothing is how the row went on naming the previous modpack",
  "-- long after the pack had changed.",
  "--",
  "-- Everything the operator owns — server_address, discord_url, the icon,",
  "-- rules_markdown — is written once and never overwritten here.",
  "INSERT INTO server_info",
  "  (id, modpack_name, modpack_version, minecraft_version, loader_name, loader_version,",
  "   download_url, wiki_url, server_address, updated_by)",
  "VALUES",
  `  (1, ${q(pack.modpackName)}, ${q(pack.modpackVersion)}, ${q(pack.minecraftVersion)},`,
  `   ${q(pack.loaderName)}, ${q(pack.loaderVersion)},`,
  `   ${q(pack.downloadUrl)}, ${q(pack.wikiUrl)}, 'tapestopnight.com', 'seed')`,
  "ON CONFLICT (id) DO UPDATE SET",
  "  modpack_name = EXCLUDED.modpack_name,",
  "  modpack_version = EXCLUDED.modpack_version,",
  "  minecraft_version = EXCLUDED.minecraft_version,",
  "  loader_name = EXCLUDED.loader_name,",
  "  loader_version = EXCLUDED.loader_version,",
  "  download_url = EXCLUDED.download_url,",
  "  wiki_url = EXCLUDED.wiki_url,",
  "  updated_by = 'seed',",
  "  updated_at = now();",
  "",
  "COMMIT;",
);

console.log(out.join("\n"));
